// Autogenerated from Pigeon (v16.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "schema.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface UserInfo ()
+ (UserInfo *)fromList:(NSArray *)list;
+ (nullable UserInfo *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation UserInfo
+ (instancetype)makeWithName:(nullable NSString *)name
    email:(nullable NSString *)email {
  UserInfo* pigeonResult = [[UserInfo alloc] init];
  pigeonResult.name = name;
  pigeonResult.email = email;
  return pigeonResult;
}
+ (UserInfo *)fromList:(NSArray *)list {
  UserInfo *pigeonResult = [[UserInfo alloc] init];
  pigeonResult.name = GetNullableObjectAtIndex(list, 0);
  pigeonResult.email = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable UserInfo *)nullableFromList:(NSArray *)list {
  return (list) ? [UserInfo fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    self.name ?: [NSNull null],
    self.email ?: [NSNull null],
  ];
}
@end

@interface UserInfoApiCodecReader : FlutterStandardReader
@end
@implementation UserInfoApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [UserInfo fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface UserInfoApiCodecWriter : FlutterStandardWriter
@end
@implementation UserInfoApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[UserInfo class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface UserInfoApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation UserInfoApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[UserInfoApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[UserInfoApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *UserInfoApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    UserInfoApiCodecReaderWriter *readerWriter = [[UserInfoApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void SetUpUserInfoApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<UserInfoApi> *api) {
  ///获取用户信息
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.cs_hello.UserInfoApi.getUserInfo"
        binaryMessenger:binaryMessenger
        codec:UserInfoApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getUserInfoWithError:)], @"UserInfoApi api (%@) doesn't respond to @selector(getUserInfoWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        UserInfo *output = [api getUserInfoWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
